version: '3.9'

services:
  server:
    build: .
    ports:
      - ${PORT}
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
